### ISSUE TITLE
Fix the dynamic inventory script

### ISSUE THREAD

**Issue by miabbott** [aweiteka/UATFramework#16]
The **central_ci_dynamic_hosts.py** script works in its current state (somehow), but it doesn't conform to what Ansible expects per the docs:

http://docs.ansible.com/developing_inventory.html

I believe that if the script followed the conventions described, we would gain the ability to specify users per host.

**Comment by aweiteka** [comment]
This issue is still relevant but I didn't want to hold up extending the script https://github.com/aweiteka/UATFramework/pull/27.

**Comment by miabbott** [comment]
Agreed.  Merging #27 was the right idea.

**Comment by aweiteka** [comment]
This script was remove from the repo by https://github.com/aweiteka/UATFramework/pull/30 since it is part of another system. UATFramework will work with any Ansible-compliant dynamic inventory script.

cc @miabbott

**Comment by miabbott** [comment]
![Feels good man](http://i2.kym-cdn.com/photos/images/original/000/125/331/feels-good-man-goat-squint-12883904505.jpg)
