### ISSUE TITLE
Migrate to Container Testing Framework

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/UATFramework#39]
[CTF](https://github.com/Containers-Testing-Framework) has a larger development and user community and has solved some problems that UATFramework has not solved. Namely, the decoupling of common and user test libraries and container-specific testing. It is not on feature parity with UAT. Known work that needs to be done is mainly around the running on remote hosts via the Ansible API.

cc @miabbott @gouyang

**Comment by miabbott** [comment]
That known work is a blocker for me, since my primary use case is testing features remotely on Atomic Host.  

Until that is solved, I can't migrate to CTF (although, I really would like to).

**Comment by vpavlin** [comment]
As far as I know (and I have actually tried that earlier) you can run tests on remote host with CTF, see
- https://github.com/Containers-Testing-Framework/ctf-cli/blob/master/README.md#configuration-file
- https://github.com/Containers-Testing-Framework/ctf-cli/blob/master/ctf_cli/common_environment.py

I don't know if you need anything specific, but let me (or CTF guys directly) know and we can figure that out.

**Comment by miabbott** [comment]
That is good to know @vpavlin.  I'll need to find some time to investigate this and report back.

**Comment by aweiteka** [comment]
https://github.com/Containers-Testing-Framework/common-steps/issues/6

**Comment by aweiteka** [comment]
CTF is so tied to docker that I don't see a reasonable path to migrating, nor does it add sufficient value above what we're doing here.
