### ISSUE TITLE
Add support for logging to file

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/UATFramework#4]
We need a log file of raw results for debugging. Use [behave logging](http://pythonhosted.org/behave/api.html#logging-capture) and log results in environment file. For example, add something like `behave.log(results)` here: https://github.com/aweiteka/UATFramework/blob/master/environment.py#L102

**Comment by miabbott** [comment]
I believe the following pull request will address this: https://github.com/aweiteka/UATFramework/pull/7
