### ISSUE TITLE
What the best way to enable sudo

### ISSUE THREAD

**Issue by gouyang** [aweiteka/UATFramework#48]
I need to add `ansible_sudo=true` in the inventory file if the Operation requires, like restart a service in PR #47, what's the best way to enable sudo? Can I do it in remote_cmd in environment.py?

**Comment by miabbott** [comment]
If you look at the `__init__()` for the `ansible.Runner` object, there is support for the  `become` attribute which is similar to using `sudo`.  See [line 155](https://github.com/ansible/ansible/blob/5ce3988d8693357f671f3fbec43b2d3b862db5f6/v1/ansible/runner/__init__.py#L155).  Also reference the Ansible docs on [Privilege Escalation](http://docs.ansible.com/become.html).

Since nearly all of our steps rely on `remote_cmd()` (which ultimately calls `ansible.runner.Runner.run()`), we would have to build in support for the `become` attribute that could be passed to the `Runner` object.

If this is done, we would have to make sure all the existing steps are not broken by the addition of this attribute.

I'm open to suggestions or PRs that attempt to solve this.  

Currently, I am using `ansible_sudo = true` in the inventory file for all the steps.

**Comment by gouyang** [comment]
@miabbott thanks for the details, the `become` attribute works.

These two methods `become` attribute  and `ansible_sudo=true` are globally affected, how to enable sudo per step?  
The quickly answer I get is adding `become=False` parameter to remote_cmd, and tranfer `become=True` argument in the exact step implementation.

**Comment by miabbott** [comment]
@gouyang I think you are correct.  We would have to default to `become=False` in the `remote_cmd()` method and then change the value to `True` in each step.

Like this perhaps?

``` python
 def remote_cmd(cmd, host=None, ignore_rc=False, become=False**kwargs):
....
        context.result = ansible.runner.Runner(
                 module_name=cmd,
                 inventory=inventory,
                 pattern=host,
                 become=become,
                 #remote_user=remote_user,
                 **kwargs
        ).run()
...
```

And then in a step

``` python
@then('"{host}" host is unsubscribed and unregistered')
def step_impl(context, host):
    '''Unregister remote host'''

    r = context.remote_cmd("command",
                            host,
                            become=True,
                            module_args="subscription-manager unregister")
    assert r
```

**Comment by gouyang** [comment]
https://github.com/gouyang/UATFramework/commit/268b29bbd17da730848b395d839be4037b426ddd

Since sudo is removed by purpose, I will update inventory file to enable sudo.

**Comment by chuanchang** [comment]
@miabbott, I still can meet the issue, the details as follows:

```
  Scenario: 3. Host provisioned and subscribed    # features/rhelah/sanity_new_qcow.feature:26
    Given "all" hosts from dynamic inventory      # steps/common.py:5 0.000s
    And "all" host                                # steps/common.py:91 7.768s
    When "all" host is auto-subscribed to "stage" # steps/redhat.py:13 50.785s
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/redhat.py", line 37, in step_impl
          module_args="subscription-manager register --username %s --password %s --auto-attach" % (user, passwd))
      AssertionError

Ansible Output: {'dark': {}, 'contacted': {XX.X.XX.XX': {u'cmd': [u'subscription-manager', u'register', u'--username', u'team6-atomic-stage', u'--password', u'redhatqa', u'--auto-attach'], u'end': u'2015-07-06 09:14:21.788231', u'stdout': u'The system has been registered with ID: adbdc127-90d1-4403-a216-c310416d670b \n\nInstalled Product Current Status:\nProduct Name:Red Hat Enterprise Linux Atomic Host\nStatus:Not Subscribed\n\nProduct Name:Red Hat Enterprise Linux Server\nStatus:Not Subscribed\n\nUnable to find available subscriptions for all your installed products.', u'changed': True, u'start': u'2015-07-06 09:13:46.772101', u'delta': u'0:00:35.016130', u'stderr': u'', u'rc': 1, 'invocation': {'module_name': 'command', 'module_args': u'subscription-manager register --username team6-atomic-stage --password XXXXXXXX --auto-attach'}, u'warnings': []}}}
    Then subscription status is ok on "all"       # None
    And "1" entitlement is consumed on "all"      # None
```

And then I gave a try manually, the result looks like this:

```
[cloud-user@team6-rhelah-72187daf-306e-4891-8ad5-50d1ad33e621 ~]$ sudo subscription-manager register --username team6-atomic-stage --password XXXXXXXX --auto-attach
The system has been registered with ID: c2d1fb0e-67a8-4b82-b0f7-476a7c0c055e 

Installed Product Current Status:
Product Name: Red Hat Enterprise Linux Atomic Host
Status:       Not Subscribed

Product Name: Red Hat Enterprise Linux Server
Status:       Not Subscribed

Unable to find available subscriptions for all your installed products.

[cloud-user@team6-rhelah-72187daf-306e-4891-8ad5-50d1ad33e621 ~]$ echo $?
1
[cloud-user@team6-rhelah-72187daf-306e-4891-8ad5-50d1ad33e621 ~]$ sudo subscription-manager list --available
No available subscription pools to list
```

Note, in fact, it indeed doesn't exist available subscription pools to list, how to resolve this? thanks.

**Comment by miabbott** [comment]
@chuanchang From your output, I believe the issue is actually with the 'team6-atomic-stage' account.  That account is not functioning correctly anymore, so I would recommend using another account.

You can contact me directly via email if you need new credentials to use.

**Comment by chuanchang** [comment]
@miabbott, okay, I will send a email to you directly, thanks.
