### ISSUE TITLE
Consider how to split apart core UAT from steps/features

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/UATFramework#59]
We're not sure [CTF](https://github.com/Containers-Testing-Framework/) is taking off. What are the options for managing a core library while providing for flexible step/feature work in other repos?
- [ ] submodules
- [ ] forks
- [ ] behave hook of some kind
- [ ] ???

**Comment by cgwalters** [comment]
While this isn't strictly on this issue, one thing I want to note here is that I feel in some cases, writing tests as plain Ansible playbook files works out quite well.

I can see Behave being _really_ awesome for certain problem domains - basically where you're not writing many steps.  But so far this module is covering a lot of ground, which means most new tests need new steps.

**Comment by aweiteka** [comment]
This framework is almost entirely focused on atomic testing so I don't see value in splitting anything apart.
